config/routes.rb
Rails.application.routes.draw do

  root 'bikes#index'
  resources :bikes

  resources :motorcycles

end

app/models/bike.rb
class Bike
	include Mongoid::Document
  field :name, type: String
  field :type, type: String
  field :speed, type: Float
 end

app/models/motorcycle.rb
class Motorcycle
  include Mongoid::Document
  field :name, type: String
  field :type, type: String
  field :speed, type: Float
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/bikes_controller.rb
class BikesController < ApplicationController
  def index
  	@bikes = Bike.all
  end

  def new
  	@bike = Bike.new
  end

  def create
  	@bike = Bike.new(bike_params)
		# if the new bean creation & save is sucessful, we want to redirect to the index
		if @bike.save
			redirect_to bikes_path
		else
			#if unsuccessful, reset to the new page
			render "new"
		end
  end

  def show
  	# retrieve one sepcific bike in our DB
		@bike = Bike.find(params[:id])
  end

  def edit
		# this action is responsible for editing a specific bike
		@bike = Bike.find(params[:id])
	end

	def update
		# this action is responsible for saving an update to a specific bike
		# this line of code retrieves a specific bean from the database
		@bike = Bike.find(params[:id])

		if @bike.update_attributes(params.require(:bike).permit(:name, :type, :speed))
			redirect_to bikes_path
		else
			#if unsuccessful, reset to the edit page
			render "edit"
		end
	end

	def destroy
		@bike = Bike.find(params[:id])
		@bike.destroy
		redirect_to bikes_path
	end

	def plus(x,y)
		x+y
	end


	private
		def bike_params
		 	params.require(:bike).permit(:name, :type, :speed)
	end
end

app/controllers/bikes_controller_spec.rb
require 'BikesController'

describe BikesController, "#plus" do
	it "adds the two numbers together" do
		bikes = Bike.all
	end
end

app/controllers/motorcycles_controller.rb
class MotorcyclesController < ApplicationController
  before_action :set_motorcycle, only: [:show, :edit, :update, :destroy]

  # GET /motorcycles
  # GET /motorcycles.json
  def index
    @motorcycles = Motorcycle.all
  end

  # GET /motorcycles/1
  # GET /motorcycles/1.json
  def show
  end

  # GET /motorcycles/new
  def new
    @motorcycle = Motorcycle.new
  end

  # GET /motorcycles/1/edit
  def edit
  end

  # POST /motorcycles
  # POST /motorcycles.json
  def create
    @motorcycle = Motorcycle.new(motorcycle_params)

    respond_to do |format|
      if @motorcycle.save
        format.html { redirect_to @motorcycle, notice: 'Motorcycle was successfully created.' }
        format.json { render :show, status: :created, location: @motorcycle }
      else
        format.html { render :new }
        format.json { render json: @motorcycle.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /motorcycles/1
  # PATCH/PUT /motorcycles/1.json
  def update
    respond_to do |format|
      if @motorcycle.update(motorcycle_params)
        format.html { redirect_to @motorcycle, notice: 'Motorcycle was successfully updated.' }
        format.json { render :show, status: :ok, location: @motorcycle }
      else
        format.html { render :edit }
        format.json { render json: @motorcycle.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /motorcycles/1
  # DELETE /motorcycles/1.json
  def destroy
    @motorcycle.destroy
    respond_to do |format|
      format.html { redirect_to motorcycles_url, notice: 'Motorcycle was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_motorcycle
      @motorcycle = Motorcycle.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def motorcycle_params
      params.require(:motorcycle).permit(:name, :type, :speed)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bikes_helper.rb
module BikesHelper
end

app/helpers/motorcycles_helper.rb
module MotorcyclesHelper
end

app/views/bikes/_finance.html.erb
<p>Backed by Dr Dre and Snoop Dogg</p>

app/views/bikes/edit.html.erb
<h1>Edit this bike!</h1>

<%= form_for @bike do |f| %>
	<%= f.label :name %> <%= f.text_field :name %>
	<%= f.label :type %> <%= f.text_field :type %>
	<%= f.label :speed %> <%= f.number_field :speed %>

	<%= f.submit "Submit yo changes!" %>

<% end %><br />

<%= link_to "Back to the list!", bikes_path %>

app/views/bikes/index.html.erb
<h1>Today's Stolen Bikes!</h1>
<h2><img src="http://rideons.files.wordpress.com/2013/04/img_3399-final.jpg"></h2>

<ul>

	<% @bikes.each do |b| %>

		<li>
			<strong><%= b.name %></strong> -- <%= b.type %> <%= b.speed %> <%= link_to "More info", bike_path(b) %>
		</li>
		
	<% end %>

</ul>



<a class="pure-button pure-button-primary" href="bikes/new">Add yo Hot bike</a>
<a class="pure-button pure-button-primary" href="motorcycles/new">Add yo Hot motobike</a>

<%= render "finance" %>

app/views/bikes/new.html.erb
<h1>Stole another bike? Add it to the list!</h1>

<%= form_for @bike do |f| %>
	<%= f.label :name %> <%= f.text_field :name %>
	<%= f.label :type %> <%= f.text_field :type %>
	<%= f.label :speed %> <%= f.number_field :speed %>

	<%= f.submit "Add this bike!!" %>

<% end %>
<br />
<%= link_to "Back to the list!", bikes_path %>

app/views/bikes/show.html.erb
<h1> <%= @bike.name %> that you stole!</h1>

<h2><img src="http://media.tumblr.com/tumblr_m9fqcwuzl11r1p25e.jpg"></h2>

<p>This <%= @bike.name %> is a <%= @bike.type %>, with a top speed of <%= @bike.speed %> mph, recently stolen and available today.</p>

<%=  link_to "Edit this bike!", edit_bike_path %>

<%= link_to "Delete this bike!", :bike, method: :delete, data: { confirm: "Are you sure you want to delete this bike?" } %>

<%= link_to "Back to the list!", bikes_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Bikes</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
	<header>
		<div class="pure-menu pure-menu-open pure-menu-horizontal">
		    <ul>
		        <li><a href="../">Home</a></li>
		        <li class="pure-menu-selected"><a href="/motorcycles">Motorcycles</a></li>
		        <li><a href="#">Thug Life Daily</a></li>
		        <li><a href="#">Stolen Stuff</a></li>
		        <li><a href="#">Finance</a></li>
		    </ul>
		</div>
	</header>
	<div id="main">
		<%= yield %>
	</div>
</body>
</html>

app/views/motorcycles/_form.html.erb
<%= form_for(@motorcycle) do |f| %>
  <% if @motorcycle.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@motorcycle.errors.count, "error") %> prohibited this motorcycle from being saved:</h2>

      <ul>
      <% @motorcycle.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :type %><br>
    <%= f.text_field :type %>
  </div>
  <div class="field">
    <%= f.label :speed %><br>
    <%= f.text_field :speed %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/motorcycles/edit.html.erb
<h1>Editing motorcycle</h1>

<%= render 'form' %>

<%= link_to 'Show', @motorcycle %> |
<%= link_to 'Back', motorcycles_path %>

app/views/motorcycles/index.html.erb
<h1>Listing motorcycles</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Type</th>
      <th>Speed</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @motorcycles.each do |motorcycle| %>
      <tr>
        <td><%= motorcycle.name %></td>
        <td><%= motorcycle.type %></td>
        <td><%= motorcycle.speed %></td>
        <td><%= link_to 'Show', motorcycle %></td>
        <td><%= link_to 'Edit', edit_motorcycle_path(motorcycle) %></td>
        <td><%= link_to 'Destroy', motorcycle, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Motorcycle', new_motorcycle_path %>

app/views/motorcycles/new.html.erb
<h1>New motorcycle</h1>

<%= render 'form' %>

<%= link_to 'Back', motorcycles_path %>

app/views/motorcycles/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @motorcycle.name %>
</p>

<p>
  <strong>Type:</strong>
  <%= @motorcycle.type %>
</p>

<p>
  <strong>Speed:</strong>
  <%= @motorcycle.speed %>
</p>

<%= link_to 'Edit', edit_motorcycle_path(@motorcycle) %> |
<%= link_to 'Back', motorcycles_path %>